//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donnes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MachineCafeContext : DbContext
    {
        public MachineCafeContext()
            : base("name=MachineCafeContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetBoisson_Result> GetBoisson(Nullable<int> idBoisson)
        {
            var idBoissonParameter = idBoisson.HasValue ?
                new ObjectParameter("idBoisson", idBoisson) :
                new ObjectParameter("idBoisson", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBoisson_Result>("GetBoisson", idBoissonParameter);
        }
    
        public virtual ObjectResult<GetSucre_Result> GetSucre(Nullable<int> idSucre)
        {
            var idSucreParameter = idSucre.HasValue ?
                new ObjectParameter("idSucre", idSucre) :
                new ObjectParameter("idSucre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSucre_Result>("GetSucre", idSucreParameter);
        }
    
        public virtual int CreatSelection(Nullable<int> idSucre, string mugPerso, Nullable<int> idBoisson)
        {
            var idSucreParameter = idSucre.HasValue ?
                new ObjectParameter("idSucre", idSucre) :
                new ObjectParameter("idSucre", typeof(int));
    
            var mugPersoParameter = mugPerso != null ?
                new ObjectParameter("mugPerso", mugPerso) :
                new ObjectParameter("mugPerso", typeof(string));
    
            var idBoissonParameter = idBoisson.HasValue ?
                new ObjectParameter("idBoisson", idBoisson) :
                new ObjectParameter("idBoisson", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreatSelection", idSucreParameter, mugPersoParameter, idBoissonParameter);
        }
    
        public virtual ObjectResult<GetLastSelection_Result3> GetLastSelection()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLastSelection_Result3>("GetLastSelection");
        }
    }
}
